# Generated by Django 3.1.7 on 2021-02-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64, null=True)),
                ('patronymic', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='client',
            name='taxpayer_id',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
        migrations.DeleteModel(
            name='LegalContact',
        ),
        migrations.AddField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_contacts', to='core.client'),
        ),
    ]
